config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :users
  resources :posts

  get 'signup', to: 'users#new', as: 'signup'
  get 'me', to: 'users#show', as: 'me'

  # Routing /dashboard to the users#dashboard method
  get 'dashboard', to: 'users#dashboard', as: 'dashboard'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :name, :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  ROLES = %w(admin editor author intern standard)

  validates :name, :email, presence: true
  validates :role, inclusion: { in: ROLES }, allow_blank: true

  def admin?
    role == 'admin'
  end

  def editor?
    role == 'editor'
  end
  
  def author?
    role == 'author'
  end

  def intern?
    role == 'intern'
  end
  
  def standard?
    role == 'standard'
  end

  def the_only_admin?
    admin? && (User.where(role: 'admin').count == 1)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  	def page_title
  		if @title 
  			@title + " | Radcircle"
  		else 
  			"Radcircle"
  		end
  	end

  	def radcircle_member
  		if !current_user.role || current_user.role.downcase == "standard" 
  			false
  		elsif current_user  			
  			true
  		end
  	end

  	helper_method :radcircle_member
  	helper_method :page_title 

  	require 'net/http'
	def facebook_likes
  		uri = URI("http://graph.facebook.com/Radcircle?fields=likes")
  		data = Net::HTTP.get(uri)
  		JSON.parse(data)['likes']
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(permitted_params)
    if @post.save
      redirect_to root_path
    else 
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(permitted_params)
      redirect_to root_path
    else
      render :edit
    end
  end

private
  def permitted_params
    params.require(:post).permit(:name,
                                 :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to root_path, notice: 'Already signed in!' if current_user
  end

  def create
    @user = login(params[:email], params[:password])
    if @user.present?
      redirect_to root_path, notice: 'Signed in!'
    else
      flash[:error] = "Email or password incorrect"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Logged out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    @title = @user.name
  end

  def new
    @user = User.new
  end

  def edit
    @admins = User.where(role: "admin")
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(permitted_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def create
    @user = User.new(permitted_params)
    @user.role = User.count.zero? ? "admin" : "standard"
    if @user.save
      auto_login(@user)
      flash[:notice] = "Thanks for signing up!"
      redirect_to root_path
    else
      render :new
    end
  end

  ## This needs to be extracted out at some point, but for now good work!
  def dashboard 
    if !current_user || !current_user.role || current_user.role.downcase == "standard"
      flash[:notice] = "You do not have access to that page!"
      redirect_to root_path
    else  
      @user = current_user
      @users = User.all.sort_by &:role
      @fb_likes = facebook_likes
      @title = "Dashboard"
    end
  end

private
  def permitted_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<%= link_to 'Home', root_path %> 
	<% if current_user %>
		<%= link_to current_user.name, me_path %>
		<% if radcircle_member %>
			<%= link_to 'Dashboard', dashboard_path %>
		<% end -%>
		<%= link_to 'sign out', logout_path %>


	<% else %>
		<%= link_to 'sign in', login_path %>
		<%= link_to 'sign up', new_user_path %>

	<% end -%>

</header>

<%= flash[:notice] %>
<%= yield %>

</body>
</html>

app/views/layouts/dashboard.html.slim
div.dashboard 
	p.name 
		| Hello 
		b = current_user.name
		| , it's great to see you today!!

	p.role 
		| Your current role:  
		= current_user.role

app/views/posts/_form.html.slim
= simple_form_for @post do |f|
  = f.input :title
  = f.input :content
  = f.submit 

app/views/posts/edit.html.slim
h1 = "Editing #{@post.title}"
= render 'form'

app/views/posts/index.html.slim
h1 Posts#index
p Find me in app/views/posts/index.html.slim

app/views/posts/new.html.slim
h1 New Post
= render 'form'

app/views/posts/show.html.slim
article
  header
    h1 = @post.title
  = raw(@post.content)

app/views/users/dashboard.html.slim
div.dashboard 
	p.name 
		| Hello 
		b = @user.name
		| , it's great to see you today!

	p.role 
		| Your current role:  
		= @user.role.humanize

	p.fb_likes
		| Radcircle's Facebook page is up to 
		b = @fb_likes 
		|  total likes now!!
	ul.navigation
		li 
			= link_to "New Post", new_post_path
		- if current_user.role.downcase == "admin"
			li 
				| users
				ul
					- @users.each do |f|
						li 
							= link_to f.name , edit_user_path(f.id)
							|  -- 
							= f.role || "standard user"

app/views/users/edit.html.slim
h1 = "Editing user #{@user.name}" 

= simple_form_for @user do |f|
  = f.input :name
  = f.input :email

  // THis should ideally be handled by Pundit, but for now (Y)
  - if current_user.the_only_admin?
    | You are the only admin, you cannot edit your role
    br
  - else
    = f.input :role, collection: User::ROLES, allow_blank: false

  = f.submit

= link_to "Back", dashboard_path

app/views/users/new.html.slim
= simple_form_for @user do |f|
  = f.input :name
  = f.input :email
  = f.input :password
  = f.submit

app/views/users/show.html.slim
h1 = current_user.name